#Programa que leia um número inteiro e mostre sua tabuada

val = (int(input('Digite um valor inteiro: ')))
a1 = (int(val*1))
a2 = (int(val*2))
a3 = (int(val*3))
a4 = (int(val*4))
a5 = (int(val*5))
a6 = (int(val*6))
a7 = (int(val*7))
a8 = (int(val*8))
a9 = (int(val*9))
a10 = (int(val*10))
print('{} X 1 = {}'.format(val,a1))
print('{} X 2 = {}'.format(val,a2))
print('{} X 3 = {}'.format(val,a3))
print('{} X 4 = {}'.format(val,a4))
print('{} X 5 = {}'.format(val,a5))
print('{} X 6 = {}'.format(val,a6))
print('{} X 7 = {}'.format(val,a7))
print('{} X 8 = {}'.format(val,a8))
print('{} X 9 = {}'.format(val,a9))
print('{} X 10 = {}'.format(val,a10))